log:
  level: "debug"

http_api_server:
  host: 0.0.0.0
  port: &http_api_server_port 8080

dns_sd:
  service_name: "data-pipelines-worker"
  service_type: "_http._tcp."
  service_domain: "local."
  service_port: *http_api_server_port
  version: "0.1"
  load: 0.0
  available: no

storage:
  storage_credentials_path: "./storage_credentials.json"

pipeline:
  pipeline_validation_schema_path: "./pipelines_validation_schema.json"
  pipeline_catalogue: "./pipelines"

openai:
  openai_credentials_path: "./openai_credentials.json"

# TODO: Block settings for Runtime and Detection 
blocks:
  http_request:
    max_retries: 3
    retry_delay: 1s
    timeout: 5s