log:
  level: "info"

# TODO: Mutual TSL for Inter Worker Comminucation

http_api_server:
  host: 0.0.0.0
  port: &http_api_server_port 8080

dns_sd:
  service_name: "data-pipelines-worker"
  service_type: "_http._tcp."
  service_domain: "local."
  service_port: *http_api_server_port
  version: "0.1"
  load: 0.0
  available: no

storage:
  local: 
    root_path: "/tmp"
  minio:
    credentials_path: "./storage_credentials.json"

pipeline:
  pipeline_validation_schema_path: "./pipelines_validation_schema.json"
  pipeline_catalogue: "./pipelines"

openai:
  credentials_path: "./openai_credentials.json"
  env_var_name: "OPENAI_API_KEY"

telegram:
  credentials_path: "./telegram_credentials.json"
  env_var_name: "TELEGRAM_BOT_TOKEN"
  bot_name: "TDIHVideoModerationBot"

blocks:
  http_request:
    detector:
      check_interval: 1m
      conditions:
        url: https://google.com
    reliability:
      policy: "exponential_backoff"
      max_retries: 5
      retry_delay: 1
      retry_codes: [500, 502, 503, 504]

  openai_chat_completion:
    detector:
      check_interval: 1m
      conditions:
    reliability:
      policy: "exponential_backoff"
      max_retries: 5
      retry_delay: 1
      retry_codes: [500, 502, 503, 504]
    config:
      model: "gpt-4o-2024-08-06"
      system_prompt: "You are a helpful assistant."
      user_prompt: "Hello ChatGPT, how are you?"

  openai_tts_request:
    detector:
      check_interval: 1m
      conditions:
    reliability:
    config:
      model: "tts-1"
      text: "Hello ChatGPT, how are you?"
      voice: "alloy"
      response_format: "mp3"
      speed: 1.0
  
  openai_transcription_request:
    detector:
      check_interval: 1m
      conditions:
    reliability:
    config:
      model: "whisper-1"
      language: "en"
      format: "verbose_json"
  
  openai_image_request:
    detector:
      check_interval: 1m
      conditions:
    reliability:
    config:
      quality: "standard"
      size: "1024x1024"
      style: "natural"

  image_add_text:
    detector:
      check_interval: 1m
      conditions:
    reliability:
      policy: "none"
    config:
      font: "Roboto-Regular.ttf"
      font_size: 50
      font_color: "#000000"
      text_position: "center-center"
      text_bg_color: "#000000"
      text_bg_all_width: true
      text_bg_alpha: 0.5
      text_bg_margin: 10 
    
  image_resize:
    detector:
      check_interval: 60m
      conditions:
    reliability:
      policy: "none"
    config:
      width: 100
      height: 100
      keep_aspect_ratio: true
  
  image_blur:
    detector:
      check_interval: 60m
      conditions:
    reliability:
      policy: "none"
    config:
      sigma: 1.5
  
  stop_pipeline:
    detector:
      check_interval: 1m
      conditions:
    reliability:
      policy: "none"
    config:
      stop: false

  send_moderation_to_telegram:
    detector:
      check_interval: 1m
      conditions:
    reliability:
      policy: "none"
    config:
      approve: "Approve"
      decline: "Decline"
      group_id: "0"
  
  fetch_moderation_from_telegram:
    detector:
      check_interval: 1m
      conditions:
    reliability:
      policy: "none"
    config:
      block_slug: ""
      stop_pipeline_if_decline: true
      retry_if_unknown: true
      retry_count: 2
      retry_interval: "30s"