log:
  level: "debug"

# TODO: Mutual TSL for Inter Worker Comminucation

http_api_server:
  host: 0.0.0.0
  port: &http_api_server_port 8080

dns_sd:
  service_name: "data-pipelines-worker"
  service_type: "_http._tcp."
  service_domain: "local."
  service_port: *http_api_server_port
  version: "0.1"
  load: 0.0
  available: no

storage:
  local: 
    root_path: "/tmp"
  minio:
    credentials_path: "./storage_credentials.json"

pipeline:
  pipeline_validation_schema_path: "./pipelines_validation_schema.json"
  pipeline_catalogue: "./pipelines"

openai:
  openai_credentials_path: "./openai_credentials.json"

blocks:
  http_request:
    detector:
      check_interval: 1m
      conditions:
        url: https://google.com
    reliability:
      policy: "exponential_backoff"
      max_retries: 5
      retry_delay: 1
      retry_codes: [500, 502, 503, 504]

  openai_chat_completion:
    detector:
      check_interval: 1m
      conditions:
        url: https://api.openai.com
    reliability:
      policy: "exponential_backoff"
      max_retries: 5
      retry_delay: 1
      retry_codes: [500, 502, 503, 504]

  image_add_text:
    detector:
      check_interval: 1m
      conditions:
        libraries: []
    reliability:
      policy: "none"
    config:
      font: /System/Library/Fonts/Supplemental/Courier New Bold.ttf
      font_size: 50
      font_color: "#000000"
      text_position: "center-center"
    
  image_resize:
    detector:
      check_interval: 60m
      conditions:
        libraries: []
    reliability:
      policy: "none"
    config:
      width: 100
      height: 100
      keep_aspect_ratio: true
