name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Prepare env for go
        run: |
          HOME="/home/data-pipelines-worker"
          GOPATH="/usr/local/go"
          echo HOME=$HOME >> $GITHUB_ENV
          echo GOPATH=$GOPATH >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true

      - name: Install dependencies
        run: go mod tidy

      - name: Build RPM
        run: make build-rpm

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v4
        with:
          name: rpm-package
          path: /home/data-pipelines-worker/rpmbuild/RPMS/x86_64/*.rpm
