name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.0'  # Specify your Go version here

      - name: Build
        run: make build  # This runs the build command defined in your Makefile

      - name: Clean up
        run: make clean  # Optional: Run the clean command defined in your Makefile
